version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    #container_name: 'tch-postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    logging:
        driver: "json-file"
        options:
           max-size: "50m"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 6432:5432

  blockscout:
    depends_on:
      - db
    #image: domecloud/blockscout-jfin-testnet
    image: domecloud/blockscout-fix-int
    restart: always
    #container_name: 'tch-blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    logging:
        driver: "json-file"
        options:
           max-size: "50m"
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'base'
        ETHEREUM_JSONRPC_HTTP_URL: http://65.108.44.103:8003/
        DATABASE_URL: postgresql://postgres:@host.docker.internal:6432/blockscout?ssl=false
        ECTO_USE_SSL: 1
    ports:
      - 4000:4000

