version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    #container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
        - ./data/postgres-data:/var/lib/postgresql/data
        - ./postgresql.conf:/etc/postgresql.conf
    #ports:
    #  - 7432:5432

  blockscout:
    depends_on:
      - db
    image: domecloud/blockscout:4.1.5
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "JFIN"
    restart: always
    #container_name: 'blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'base'
        ETHEREUM_JSONRPC_HTTP_URL: http://65.108.100.176:8545/
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
        COIN: JFIN
        COINGECKO_COIN_ID: jfin-coin
        NETWORK: JFIN
        SUBNETWORK: Mainnet
    ports:
      - 4000:4000

